const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
function game(saved){const els=new Map();const get=id=>{if(!els.has(id))els.set(id,{innerHTML:'',textContent:'',value:'',open:false,addEventListener(){},setAttribute(){},getBoundingClientRect(){return {left:0,top:0,width:50,height:50}},append(){},remove(){},style:{},classList:{add(){},remove(){}},showModal(){this.open=true;},close(){this.open=false;}});return els.get(id);};let data=saved;const ctx=vm.createContext({document:{getElementById:get,querySelector:()=>null,addEventListener(){},createElement:()=>get('effect')},window:{matchMedia:()=>({matches:true})},navigator:{},localStorage:{getItem:()=>data,setItem:(k,v)=>data=v},setInterval(){},setTimeout(){},clearTimeout(){},Date,Math});vm.runInContext(fs.readFileSync(__dirname+'/../math/game.js','utf8'),ctx);return{run:s=>vm.runInContext(s,ctx),get,saved:()=>data};}
test('wrong answers preserve inventory and currency',()=>{const g=game();g.run('counts=counts.map(()=>0);deliver()');assert.equal(g.run('state.coins'),24);assert.equal(g.run('state.stock[0]'),12);assert.equal(g.run('state.completed'),0);});
test('correct answer with insufficient stock retains order',()=>{const g=game();g.run('state.stock[0]=0;counts=counts.map(()=>state.order.each);deliver()');assert.equal(g.run('state.completed'),0);assert.match(g.get('feedback').textContent,/계산은 맞았어요/);});
test('all four order kinds pay once and retain remainder',()=>{for(const kind of ['multiply','divide','group','remainder']){const g=game();g.run(`state.order={kind:'${kind}',crop:0,groups:3,each:4,rest:${kind==='remainder'?2:0},friend:0};state.stock[0]=20;mode='calc'`);g.get('answer').value=kind==='multiply'?'12':kind==='divide'?'4':'3';g.get('remainder').value='2';g.run('deliver()');assert.equal(g.run('state.completed'),0);assert.equal(g.run('state.stock[0]'),20);g.run('completeSale()');assert.equal(g.run('state.completed'),1);assert.equal(g.run('state.stock[0]'),8);assert.equal(g.run('state.coins'),53);assert.equal(g.run('phase'),'success');g.run('completeSale();deliver()');assert.equal(g.run('state.completed'),1);}});
test('plant consumes seed; ripe harvest adds crop exactly once',()=>{const g=game();g.run("$('plots').onclick({target:{closest:()=>({dataset:{plot:'1'},getBoundingClientRect:()=>({left:0,top:0,width:50})})}})");assert.equal(g.run('state.seeds[0]'),2);g.run('state.plots[1].ready=0');g.run("$('plots').onclick({target:{closest:()=>({dataset:{plot:'1'},getBoundingClientRect:()=>({left:0,top:0,width:50})})}})");assert.equal(g.run('state.stock[0]'),24);assert.equal(g.run('state.plots[1]'),null);});
test('saved farm survives load; invalid save recovers',()=>{const g=game();g.run('state.coins=123;save()');assert.equal(game(g.saved()).run('state.coins'),123);assert.equal(game('{oops').run('state.coins'),24);assert.equal(game(JSON.stringify({version:1,coins:-3})).run('state.coins'),24);});

test('incorrect change cannot sell, exact change adds only sale price once',()=>{const g=game();g.run("state.completed=2;state.order={kind:'multiply',crop:0,groups:3,each:4,rest:0,friend:0};state.stock[0]=20;mode='calc'");g.get('answer').value='12';g.run('deliver();addCoin(5);completeSale()');assert.equal(g.run('phase'),'payment');assert.equal(g.run('state.stock[0]'),20);assert.equal(g.run('state.coins'),24);g.run('changeCoins=[];addCoin(1);completeSale();completeSale()');assert.equal(g.run('state.coins'),53);assert.equal(g.run('state.stock[0]'),8);});
test('refresh during payment preserves goods and money without granting rewards',()=>{const g=game();g.run("state.order={kind:'multiply',crop:0,groups:3,each:4,rest:0,friend:0};state.stock[0]=20;mode='calc';save()");g.get('answer').value='12';g.run('deliver()');const loaded=game(g.saved());assert.equal(loaded.run('phase'),'packing');assert.equal(loaded.run('state.coins'),24);assert.equal(loaded.run('state.stock[0]'),20);});
test('packing cannot take more than available inventory; moving between places preserves it',()=>{const g=game();g.run('state.stock[0]=1;fillBag(0);fillBag(0);setPlace("market");setPlace("farm")');assert.equal(g.run('counts[0]'),1);assert.equal(g.run('state.stock[0]'),1);assert.equal(g.run('place'),'farm');});

test('cancelling checkout returns to packing with no stock or coin change',()=>{const g=game();g.run("state.order={kind:'multiply',crop:0,groups:2,each:3,rest:0,friend:0};counts=[3,3];deliver();$('unpack').onclick()");assert.equal(g.run('phase'),'packing');assert.equal(g.run('state.stock[0]'),12);assert.equal(g.run('state.coins'),24);assert.equal(g.get('next').disabled,false);});
test('decoration purchase charges on placement once and moving is free',()=>{const g=game();g.run('state.coins=100;state.completed=5;selectDecoration(3)');assert.equal(g.run('state.coins'),100);g.run('placeDecoration(1)');assert.equal(g.run('state.coins'),35);assert.equal(g.run('state.decorSlots[1]'),3);g.run('selectDecoration(3);placeDecoration(2)');assert.equal(g.run('state.coins'),35);assert.equal(g.run('state.decorSlots[1]'),null);assert.equal(g.run('state.decorSlots[2]'),3);});
test('locked decoration and cancelled placement never spend coins',()=>{const g=game();g.run('state.coins=200;selectDecoration(5)');assert.equal(g.run('placing'),null);g.run('selectDecoration(0);cancelPlacement();placeDecoration(0)');assert.equal(g.run('state.coins'),200);assert.equal(g.run('state.decorSlots[0]'),null);});
test('legacy decoration and purchased placements survive saving',()=>{const g=game();g.run('state.decor=2;delete state.ownedDecor;delete state.decorSlots;save()');const migrated=game(g.saved());assert.equal(migrated.run('state.decorSlots[1]'),1);migrated.run('save()');assert.equal(game(migrated.saved()).run('state.ownedDecor.length'),2);});
