'use strict';
const CROPS=[{name:'당근',icon:'🥕',cost:0,yield:12,time:8000},{name:'딸기',icon:'🍓',cost:6,yield:12,time:12000},{name:'토마토',icon:'🍅',cost:8,yield:15,time:16000}];
const FRIENDS=[{name:'토끼 모모',kind:'rabbit',color:'#fff9ee'},{name:'곰 두두',kind:'bear',color:'#d9b18b'},{name:'고양이 나나',kind:'cat',color:'#f5cd89'},{name:'토끼 코코',kind:'rabbit',color:'#e9e3f5'}];
const KEY='mongle-math-farm-v1';
const initial=()=>({version:1,coins:24,seeds:[3,1,1],stock:[12,0,0],plots:[{crop:0,ready:Date.now()-1},null,null,null,null,null],completed:0,decor:0,difficulty:1,order:null});
function validState(s){return s&&s.version===1&&Number.isSafeInteger(s.coins)&&s.coins>=0&&Number.isSafeInteger(s.completed)&&s.completed>=0&&Number.isInteger(s.decor)&&s.decor>=0&&s.decor<=3&&[1,2].includes(s.difficulty)&&['seeds','stock'].every(k=>Array.isArray(s[k])&&s[k].length===3&&s[k].every(n=>Number.isSafeInteger(n)&&n>=0))&&Array.isArray(s.plots)&&s.plots.length===6&&s.plots.every(p=>p===null||(Number.isInteger(p.crop)&&p.crop>=0&&p.crop<3&&Number.isFinite(p.ready)))&&(!s.order||(Number.isInteger(s.order.crop)&&s.order.crop>=0&&s.order.crop<3&&['multiply','divide','group','remainder'].includes(s.order.kind)&&Number.isInteger(s.order.each)&&s.order.each>0&&s.order.each<=12&&Number.isInteger(s.order.groups)&&s.order.groups>0&&s.order.groups<=6&&Number.isInteger(s.order.rest)&&s.order.rest>=0&&s.order.rest<s.order.each&&Number.isInteger(s.order.friend)&&s.order.friend>=0&&s.order.friend<4));}
let state=initial(),storageOK=true;
try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw);if(validState(parsed))state=parsed;}}catch{storageOK=false;}
let selected=0,mode='manual',counts=[],toastTimer;
const $=id=>document.getElementById(id);
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;}catch{storageOK=false;}$('save-status').textContent=storageOK?'이 기기에 자동 저장돼요':'저장할 수 없어 창을 닫으면 진행이 사라져요';}
function animal(friend){const c=friend.color;let ears=friend.kind==='rabbit'?`<ellipse cx="36" cy="30" rx="12" ry="27" fill="${c}"/><ellipse cx="73" cy="30" rx="12" ry="27" fill="${c}"/><ellipse cx="36" cy="28" rx="5" ry="18" fill="#f2b8bd"/><ellipse cx="73" cy="28" rx="5" ry="18" fill="#f2b8bd"/>`:friend.kind==='cat'?`<path d="M18 55 L17 15 L46 39 M64 39 L91 15 L94 56" fill="${c}" stroke="${c}" stroke-width="8" stroke-linejoin="round"/>`:`<circle cx="22" cy="36" r="18" fill="${c}"/><circle cx="86" cy="36" r="18" fill="${c}"/><circle cx="22" cy="36" r="9" fill="#e8c8b5"/><circle cx="86" cy="36" r="9" fill="#e8c8b5"/>`;return `<svg viewBox="0 0 110 130" aria-hidden="true">${ears}<ellipse cx="55" cy="108" rx="34" ry="27" fill="#92ac7a"/><ellipse cx="55" cy="68" rx="44" ry="37" fill="${c}"/><ellipse cx="29" cy="77" rx="9" ry="5" fill="#f0b1b2"/><ellipse cx="81" cy="77" rx="9" ry="5" fill="#f0b1b2"/><circle cx="39" cy="65" r="3.5" fill="#514136"/><circle cx="71" cy="65" r="3.5" fill="#514136"/><path d="M51 74 Q55 78 59 74 M55 78 Q49 85 45 79 M55 78 Q61 85 65 79" fill="none" stroke="#75534a" stroke-width="2.4" stroke-linecap="round"/><path d="M40 98 L40 126 L73 126 L73 98" fill="#f4e5bb"/><circle cx="46" cy="105" r="2" fill="#a1ad74"/><circle cx="66" cy="105" r="2" fill="#a1ad74"/></svg>`;}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3000);}
function newOrder(){const n=state.completed;const kind=state.difficulty===2?['multiply','divide','group','remainder'][n%4]:['multiply','divide','group'][n%3];const crop=n===0?0:Math.floor(Math.random()*3);const groups=2+Math.floor(Math.random()*3);const each=state.difficulty===2?6+Math.floor(Math.random()*7):2+Math.floor(Math.random()*4);state.order={kind,crop,groups,each,rest:kind==='remainder'?1+Math.floor(Math.random()*(each-1)):0,friend:n%4};resetPacking();save();}
function resetPacking(){counts=Array(state.order.groups).fill(0);$('feedback').textContent='';}
function total(o=state.order){return o.groups*o.each+o.rest;}
function answer(o=state.order){return o.kind==='multiply'?total(o):o.kind==='divide'?o.each:o.groups;}
function reward(){return (total()-state.order.rest)*2+5;}
function renderFarm(){ $('coins').textContent=state.coins;$('level').textContent=state.completed<5?'🌱 새싹 농부':state.completed<15?'🌿 쑥쑥 농부':'🌻 멋진 농부';$('progress').textContent=`주문 ${state.completed}개 완료`; $('goal-text').textContent=state.decor===3?'꽃길과 버섯, 무지개까지! 농장이 활짝 피었어요.':`주문을 해결하고 꽃밭을 꾸며 보세요. (${state.decor}/3)`;$('decorate').disabled=state.decor===3;$('decorate').textContent=state.decor===3?'꾸미기 완료 ♡':'꾸미기 · 40 🪙';$('decor').textContent=['🌼　🌱　🌼','🌷　🌼　🌷　🌼','🌷　🍄　🌼　🍄　🌷','🌷　🍄　🌈　🍄　🌷'][state.decor];$('seeds').innerHTML=CROPS.map((c,i)=>`<button class="seed ${selected===i?'selected':''}" data-seed="${i}" aria-label="${c.name} 씨앗 선택, ${state.seeds[i]}개" aria-pressed="${selected===i}">${c.icon}<small>씨앗 ${state.seeds[i]}</small></button>`).join('');$('inventory').innerHTML=CROPS.map((c,i)=>`<div><span>${c.icon}</span><div>${c.name}<br><b>${state.stock[i]}</b> <small>개</small></div></div>`).join('');renderPlots();}
function renderPlots(){const now=Date.now();const markup=state.plots.map((p,i)=>{if(!p)return `<button class="plot empty" data-plot="${i}" aria-label="${i+1}번 빈 밭에 ${CROPS[selected].name} 심기">＋</button>`;const ready=p.ready<=now,c=CROPS[p.crop];return `<button class="plot ${ready?'ready':''}" data-plot="${i}" aria-label="${i+1}번 밭 ${c.name} ${ready?'수확하기':'자라는 중'}"><span class="plant">${ready?c.icon:'🌱'}</span><small>${ready?'수확 +'+c.yield:Math.ceil((p.ready-now)/1000)+'초'}</small></button>`;}).join('');if($('plots').innerHTML!==markup)$('plots').innerHTML=markup;}
function renderOrder(){const o=state.order,c=CROPS[o.crop];$('order-kind').textContent={multiply:'곱셈',divide:'나눗셈 · 똑같이',group:'나눗셈 · 묶음',remainder:'나눗셈 · 나머지'}[o.kind];$('animal').innerHTML=animal(FRIENDS[o.friend]);$('customer-name').textContent=FRIENDS[o.friend].name;let text=o.kind==='multiply'?`${c.name}을 한 바구니에 ${o.each}개씩, ${o.groups}바구니 주세요!`:o.kind==='divide'?`${c.name} ${total()}개를 ${o.groups}바구니에 똑같이 나누어 주세요!`:`${c.name} ${total()}개를 ${o.each}개씩 담으면 몇 바구니일까요?${o.rest?' 남은 개수도 알려 주세요!':''}`;$('order-text').textContent=text;$('reward').textContent=`${c.icon} 필요한 작물 ${total()}개 · 판매 보상 ${reward()}코인`;$('difficulty').value=state.difficulty;renderPacking();}
function renderPacking(){const o=state.order,c=CROPS[o.crop];$('manual-mode').setAttribute('aria-pressed',String(mode==='manual'));$('calc-mode').setAttribute('aria-pressed',String(mode==='calc'));if(mode==='manual'){$('packing').innerHTML=`<div class="baskets">${counts.map((n,i)=>`<div class="basket"><div class="items">${n?c.icon.repeat(Math.min(n,12)):'🧺'}</div><b>${i+1}번 · ${n}개</b><div class="basket-controls"><button data-minus="${i}" aria-label="${i+1}번 바구니에서 하나 빼기">−</button><button data-plus="${i}" aria-label="${i+1}번 바구니에 하나 담기">＋</button></div></div>`).join('')}</div><p class="pack-note">＋로 하나씩 담고, −로 다시 꺼내요. (${counts.reduce((a,b)=>a+b,0)}/${total()}개)</p>${o.kind==='group'||o.kind==='remainder'?`<div class="calc-form"><label>바구니 <input id="answer" type="number" inputmode="numeric" min="0" aria-label="바구니 수"> 개</label>${o.rest?'<label>남은 작물 <input id="remainder" type="number" inputmode="numeric" min="0" aria-label="나머지"> 개</label>':''}</div>`:''}`;}else{$('packing').innerHTML=`<div class="calc-form"><span>${o.kind==='multiply'?`${o.each} × ${o.groups}`:`${total()} ÷ ${o.kind==='divide'?o.groups:o.each}`} =</span><input id="answer" type="number" inputmode="numeric" min="0" aria-label="계산 답">${o.rest?'<label>나머지 <input id="remainder" type="number" inputmode="numeric" min="0" aria-label="나머지"></label>':''}</div><p class="pack-note">${o.kind==='multiply'?'필요한 작물은 모두 몇 개일까요?':o.kind==='divide'?'한 바구니에 몇 개씩 담을까요?':'몇 바구니를 만들 수 있을까요?'}</p>`;}}
function readNumber(id){const el=$(id);return el&&el.value.trim()!==''?Number(el.value):NaN;}
function deliver(){if($('modal').open)return;const o=state.order;let correct=mode==='manual'?counts.every(n=>n===o.each):readNumber('answer')===answer();if(mode==='manual'&&(o.kind==='group'||o.kind==='remainder'))correct=correct&&readNumber('answer')===o.groups;if(o.rest)correct=correct&&readNumber('remainder')===o.rest;if(!correct){$('feedback').textContent=mode==='manual'?`한 바구니에 같은 수로 담아 보세요. ${o.kind==='multiply'?o.each+'개씩이에요!':'💡 버튼으로 함께 생각할 수 있어요.'}`:'괜찮아요! 직접 담기나 💡 힌트로 다시 생각해 봐요.';return;}if(state.stock[o.crop]<total()){$('feedback').textContent=`계산은 맞았어요! ${CROPS[o.crop].name} ${total()-state.stock[o.crop]}개를 더 수확해 주세요. 포장은 그대로 기다릴게요.`;return;}const paid=reward();state.stock[o.crop]-=total()-o.rest;state.coins+=paid;state.completed++;toast(`참 잘했어요! ${paid}코인을 받았어요 ♡${o.rest?' 남은 작물은 바구니에 보관했어요.':''}`);newOrder();renderFarm();renderOrder();showModal('정말 잘했어요! ♡',`<div class="success-animal">${animal(FRIENDS[o.friend])}</div><p class="success-equation">${o.each} × ${o.groups} = ${o.each*o.groups}</p><div class="baskets">${Array(o.groups).fill(`<div class="basket"><div class="items">${CROPS[o.crop].icon.repeat(o.each)}</div><b>${o.each}개</b></div>`).join('')}</div><p>${o.groups}바구니에 ${o.each}개씩 포장했어요.${o.rest?` 남은 ${o.rest}개는 보관했어요.`:''}<br>🪙 ${paid}코인을 받았어요!</p><button class="primary" data-continue>다음 손님 만나기 →</button>`);}
$('seeds').onclick=e=>{const b=e.target.closest('[data-seed]');if(!b)return;selected=Number(b.dataset.seed);renderFarm();};
$('plots').onclick=e=>{const b=e.target.closest('[data-plot]');if(!b)return;const i=Number(b.dataset.plot),p=state.plots[i];if(p){if(Date.now()<p.ready){toast('햇살을 먹으며 쑥쑥 자라고 있어요!');return;}state.stock[p.crop]+=CROPS[p.crop].yield;toast(`${CROPS[p.crop].icon} ${CROPS[p.crop].name} ${CROPS[p.crop].yield}개 수확!`);state.plots[i]=null;}else{if(!state.seeds[selected]){toast('씨앗 상점에서 씨앗을 받아 주세요.');openShop();return;}state.seeds[selected]--;state.plots[i]={crop:selected,ready:Date.now()+CROPS[selected].time};}save();renderFarm();};
$('packing').onclick=e=>{const plus=e.target.closest('[data-plus]'),minus=e.target.closest('[data-minus]');if(!plus&&!minus)return;const i=Number((plus||minus).dataset[plus?'plus':'minus']);if(plus){if(counts.reduce((a,b)=>a+b,0)>=total()){toast('주문에 필요한 작물은 모두 꺼냈어요. 골고루 나누어 볼까요?');return;}counts[i]++;}else counts[i]=Math.max(0,counts[i]-1);const a=$('answer')?.value,r=$('remainder')?.value;renderPacking();if($('answer')&&a!==undefined)$('answer').value=a;if($('remainder')&&r!==undefined)$('remainder').value=r;};
$('manual-mode').onclick=()=>{mode='manual';renderPacking();};$('calc-mode').onclick=()=>{mode='calc';renderPacking();};$('deliver').onclick=deliver;$('packing').onkeydown=e=>{if(e.key==='Enter')deliver();};
$('hint').onclick=()=>{const o=state.order;$('feedback').textContent=o.kind==='multiply'?`${o.each}개를 ${o.groups}번 모아요. ${Array(o.groups).fill(o.each).join(' + ')} = ?`:o.kind==='divide'?`${total()}개를 ${o.groups}곳에 하나씩 나누어 놓아 보세요. ${o.groups} × □ = ${total()}`:`${o.each}개씩 묶어 보세요. ${o.each} × □${o.rest?' + 나머지':''} = ${total()}`;};
$('next').onclick=()=>{newOrder();renderOrder();toast('다른 주문을 가져왔어요. 작물은 그대로예요.');};$('difficulty').onchange=()=>{state.difficulty=Number($('difficulty').value);newOrder();renderOrder();};
function showModal(title,html){$('modal-title').textContent=title;$('modal-body').innerHTML=html;if(!$('modal').open)$('modal').showModal();}
function openShop(){showModal('🌱 모모의 씨앗 상점',`<p>씨앗 1개로 여러 개를 수확해요.<br>당근 씨앗은 언제든 무료로 받을 수 있어요!</p>${CROPS.map((c,i)=>`<div class="shop-item"><span>${c.icon}</span><div><b>${c.name} 씨앗</b><small>${c.time/1000}초 후 ${c.yield}개 수확 · 보유 ${state.seeds[i]}개</small></div><button class="small" data-buy="${i}" ${state.coins<c.cost?'disabled':''}>${c.cost?c.cost+' 🪙':'무료로 받기'}</button></div>`).join('')}`);}
$('shop-open').onclick=openShop;$('modal-body').onclick=e=>{if(e.target.closest('[data-continue]')){$('modal').close();return;}const b=e.target.closest('[data-buy]');if(!b)return;const i=Number(b.dataset.buy);if(state.coins<CROPS[i].cost)return;state.coins-=CROPS[i].cost;state.seeds[i]++;save();renderFarm();openShop();toast(`${CROPS[i].name} 씨앗을 받았어요!`);};$('close-modal').onclick=()=>$('modal').close();
$('help').onclick=()=>showModal('우리 농장에 오신 걸 환영해요 ♡','<ol class="help-steps"><li>씨앗을 고르고 빈 밭을 눌러 심어요.</li><li>8~16초 뒤 작물을 눌러 수확해요.</li><li>동물 손님의 주문을 읽어요.</li><li>＋로 직접 담거나 계산 답을 적어요.</li><li>건네주고 받은 코인으로 씨앗과 장식을 사요!</li></ol><p>틀려도 괜찮아요. 코인과 작물은 사라지지 않아요. 포장 연습은 수확 전에도 할 수 있어요.</p><p>학습 단계 2에서는 더 큰 수와 나머지가 등장해요. 진행은 이 브라우저에 저장돼요.</p>');
$('decorate').onclick=()=>{if(state.decor>=3)return;if(state.coins<40){toast(`꾸미려면 ${40-state.coins}코인이 더 필요해요.`);return;}state.coins-=40;state.decor++;save();renderFarm();toast('농장이 더 사랑스러워졌어요! 🌷');};
$('farmer').innerHTML=animal(FRIENDS[0]);if(!state.order)newOrder();else resetPacking();renderFarm();renderOrder();save();setInterval(renderPlots,1000);
if('serviceWorker'in navigator)navigator.serviceWorker.register('../sw.js').catch(()=>{});
